

# This file was *autogenerated* from the file 1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_24 = Integer(24); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3)# Mateusz Karpiński
# WCY23KY1S1
# Laboratoria 3: Podzial Wiadomosci Pofunych

import random


print("Krok 1: Znalezienie p, wylosowanie M oraz ustawienia n = 10 i k = 5")
u = _sage_const_2 **_sage_const_24 
p = next_prime(u)
M = random.randint(_sage_const_1 , p)
n = _sage_const_10 
k = _sage_const_5 

# M - wiadomosc
print("M: ", M)
# n - liczba cieni
print("n: ", n)
# k - liczba potrzebna do odtworzenia wiadomości M
print("k: ", k)
# p - liczba pierwsza > n, > M
print("p: ", p)



print()
print()
print()

print("Krok 2: Wygenerowanie wielomianu stopnia k-1 (wylosowanie wspolczynnikow a_i)")

F = GF(p)

a = []

# dodanie elementu wolengo w wielomianie
a.append(M)

for i in range(_sage_const_0 , k-_sage_const_1 ):
    a.append(F.random_element())


print("Tablica wspolczynnikow (oraz M jako element wolny): ", a)

P = F['x']; (x,) = P._first_ngens(1)
f = sum([a[i] * x**i for i in range(len(a))])
print("f: ", f)


# wygenerowanie pierscienia wielomianu i wielomianu

# tablica uzytkownikow i cieni
# l = zero_matrix(F, n, 2)
l = zero_matrix(n, _sage_const_3 )


print()
print()
print()

print("Krok 3: Wyznaczenie cieni poprzez wyznaczenie wartosci wielomianu w n roznych punkach")
print("Krok 4: Wyslanie do poszczegolnych uzytkownikow systemu x_i oraz odpowiadajaca jej wartosci l_i, oraz liczbe pierwsza p")
# wygenerowanie cieni
for i in range(n):
    x_i = i+_sage_const_1 
    r = random.randint(_sage_const_1 , p)
    l[i, _sage_const_0 ] = r
    l[i, _sage_const_1 ] = f(r)
    l[i, _sage_const_2 ] = p

print()
print()

print("Cienie l (x_i, l_i, p):")
print(l)

print()
print()
print()

print("Krok 5: Wyznaczenie M, przez zebranie dowolnego podzbioru k osob posiadajacych cienie. (Poprzez rozwiazanie ukladu kongruencji z k niewiadomymi)")

print("Krok 5.1 Wybranie k losowych osob")

KM = random.sample(range(n), k)

print("Losowo wybrane osoby: ", KM)
for i in KM:
    print(f"KM indeks: {i}, x_i = l[{i}, 0] = {l[i,_sage_const_0 ]}, l_i = {l[i,_sage_const_1 ]}")


print("Aby odtworzyc f nalezy rozwiazac uklad kongruencji: A * a = B, gdzie:")
print("A - macierz z x do potegi")
print("a - wektor wspolczynnikow wielomianu - szukana")
print("B - wektor wartosci wielomianu (f(x_i))")

A = zero_matrix(F, k, k)
a = zero_vector(F, k)
B = zero_vector(F, k)

# zapelnienie A oraz B

for i in range(k):
    x_i = l[KM[i], _sage_const_0 ]
    B[i] = l[KM[i], _sage_const_1 ]
    for j in range(k):
        A[i, j] = x_i**j


print()
print()
print()

print("Rownanie A * a = B: ")
print(A," * (w_1, w_2, w_3, w_4, w_5)^T = ", B, "^T")
print()
print()
print("Gdzie w_i to szukane wspolczynniki wielomianu")

# rozwiazanie rownania
a = A.solve_right(B)


print()
print()
print()

print("Otrzymane a (wspolczynniki): ", a)
print("Wiadomo, ze a_0 = M, stad M = ", a[_sage_const_0 ])
print("M z poczatku zadnia: ", M)

if (M == a[_sage_const_0 ]):
    print("Wiadomosci sa takie same")
else:
    print("Wiadomosci nie sa takie same")

print()
print()
print()
print("Sprawdzenie wszystkich cieni z otrzymanym wielomianem:")

f_odtworzony = sum([a[i] * x**i for i in range(k)])

print("Odtworzony wielomian: ", f_odtworzony)

for i in range(n):
    x_i = l[i, _sage_const_0 ]
    oryginalny = l[i, _sage_const_1 ]
    odtworzony = f_odtworzony(x_i)
    print(f"x = {x_i}, oryginalny: {oryginalny}, odtworzony: {odtworzony}")

