

# This file was *autogenerated* from the file 2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_4 = Integer(4); _sage_const_1234567890 = Integer(1234567890)# zadanie 2
# lamport
import random
import hashlib

n = _sage_const_10 
t = _sage_const_4 

print("Krok 1")
x = _sage_const_1234567890 
dane = []
dane.append(x)
print('x = ', x)
print("generowanie hasel")

d = hashlib.sha3_512()
d.update(x.str().encode())
hash = d.hexdigest()
dane.append(hash)

for i in range(_sage_const_10 ):
    x = hash
    d.update(x.encode())
    hash = d.hexdigest()
    dane.append(hash)

print()
print(dane)




print()
print("Krok 2")
print("System sprawdza")
if (x in dane):
    print("uzytkownik istnieje zapytanie o haslo")
print("Krok 3")
print("Krok 4")

