

# This file was *autogenerated* from the file 1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_64 = Integer(64); _sage_const_32 = Integer(32); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)# Mateusz Karpiński 
# WCY23KY1S1
# Uczciwe rzucanie moneta

import random

# parametry wejsciowe
# b1, b2 w bitach
b1 = _sage_const_64 
b2 = _sage_const_32 
print("b1 = ", b1)
print("b2 = ", b2)

print("Wygenerowanie liczb p i q")
p = next_prime(random.getrandbits(b1))
while p % _sage_const_4  != _sage_const_3 :
    p = next_prime(p)
    
q = next_prime(random.getrandbits(b2))
while q % _sage_const_4  != _sage_const_3 :
    q = next_prime(q)

print("p = ", p)
print("q = ", q)

# 1. uzytkownik A generiuje liczbe calkowita Bluma n, losowe x wzglednie pierwsze z n
print("1.1 Uzytkownik A generuje liczbe calkowita Bluma")
n = p * q
print("Liczba calkowita Bluma: n = p*q")
print("n = ", n)

print("1.2 Uzytkownik A generuje losowe x wzglednie pierwsze z n")
while True:
    x = random.randint(_sage_const_2 , n-_sage_const_1 )
    if gcd(x, n) == _sage_const_1 :
        break
print("x = ", x)

# 2.uzytkownik A oblicza:
print()
print()
print()
print("2.1 Uzytkownik A oblicza: ")
print("x0 = x^2 (mod n)")
x0 = pow(x, _sage_const_2 , n)
# x_0 = x^2 (mod n)
print("x1 = x0^2 (mod n)")
# x_1 = x_0^2 (mod n)
x1 = pow(x0, _sage_const_2 , n)
print("x0 = ", x0)
print("x1 = ", x1)
# i przesyla n i x_1 do uzytkownika B
print("n i x1 sa przeslane do uzytkownika B")


# 3. uzytkownik B odgaduje czy x_0 jest przyste, czy nieparzyste
print("3.1 Uzytkownik B odgaduje czy x0 jest parzyste czy nie")
guess = random.randint(_sage_const_0 , _sage_const_1 )  # 0 - parzyste, 1 - nieparzyste
if guess == _sage_const_0 :
    print("B odgaduje, ze x0 jest parzyste")
else:
    print("B odgaduje, ze x0 jest nieparzyste")


# 4. uzytkownik A przesyla do B x i x_0
print("4.1 Uzytkownik A przesyla do B x i x0")

# 5. uzytkownik B sprawdza, czy n jest liczba calkowita Bluma (uzytkownik A powinien przekazac do B czynniki liczby n lub zrealizowac protokol o wiedzy 'zerowej' w celu przekonania go, ze jest rzeczywiscie liczba calkowita Bluma) i czy x_0 = x^2 (mod n) oraz x_1 = x_0^2 (mod n), jezeli wszystko sie zgadza, to wynikiem rzutu moneta jest: orzel jezeli uzytkownik B odgadl poprawnie parzystosc/nieparzystosc x0; reszka w przeciwnym wypadku

# sposob 1: przekazanie czynnikow liczby n
print("5.1 A przesyla czynniki n do B")
print("5.2 B sprawdza czy rzeczywiscie jest to liczba calkowita Bluma i czy sie wszystko zgadza")

x0b = pow(x, _sage_const_2 , n)
x1b = pow(x0, _sage_const_2 , n)
if int(x0)%_sage_const_2  == _sage_const_0 :
    result = _sage_const_0 
else:
    result = _sage_const_1 

if p%_sage_const_4 ==_sage_const_3  and q%_sage_const_4 ==_sage_const_3  and x0b == x0 and x1b == x1:
    print("Wszystko sie zgadza")
    if guess == result:
        print("Wynik: Orzeł")
    else:
        print("Wynik: Reszka")
else:
    print("Cos sie nie zgadza - koniec programu")


# sposob 2: zrealizowac protokol o wiedzy 'zerowej'

