

# This file was *autogenerated* from the file zad1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_128 = Integer(128); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_2 = Integer(2)# Mateusz Karpiński WCY23KY1S1
# na 4 punkty do 8 kwietnia 

import random


b = _sage_const_128 
n = next_prime(_sage_const_1 *_sage_const_10 **_sage_const_15 )
p = _sage_const_2 *n+_sage_const_1 
while not is_prime(p):
    n = next_prime(n)
    p = _sage_const_2 *n+_sage_const_1 

print(n)
print(p)

# inicjacja ciała F
F = GF(p)

g = F.random_element()

print(g.multiplicative_order())

xa = random.randint(_sage_const_1 , n-_sage_const_1 )

