

# This file was *autogenerated* from the file przyg.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100)
from sage.crypto.util import random_prime
print(random_prime(_sage_const_100 ))

